#Spring Config Server 설정
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saruan/SPGateway.git
          search-paths:
          - 'Properties/'
          password: rnrudxo1184018
          username: kookyungte@naver.com
    bus:
      enabled: true
  kafka:
    bootstrap-servers:
    - http://localhost:9092
  application:
    name: config-server
  
    
#Actuactor 활성화    
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ['bus-refresh']
             
server:
  port: 9999