#Spring Config Server 설정
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saruan/SPGateway.git
          search-paths:
            - 'GatewayConfig/*'
          password: ENC(nltSdYaxt41whAkHAj4Q5fchiL7tJE0l)
          username: kookyungte@naver.com
    bus:
      enabled: true
  # RabbitMQ 설정
  rabbitmq:
    host: 211.62.204.27
    port: 5672
    username: gateway
    password: gateway
  application:
    name: config-server
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

#Actuactor 활성화    
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ['bus-refresh', 'refresh']

server:
  port: 9999